/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ScanCode: typeof import('./src/components/scan-code/index.vue')['default']
    Spin: typeof import('./src/components/Spin/index.vue')['default']
  }
}
